// Code generated by diho_bytes_generate auth.go; DO NOT EDIT.

package packets

import (
	"bytes"
	"context"
	"encoding/binary"
	utils "github.com/Nyarum/diho_bytes_generate/utils"
)

func (p *Auth) Decode(ctx context.Context, buf []byte, endian binary.ByteOrder) error {
	var err error
	reader := bytes.NewReader(buf)
	p.Key, err = utils.ReadBytes(reader)
	if err != nil {
		return err
	}
	p.Login, err = utils.ReadStringNull(reader)
	if err != nil {
		return err
	}
	p.Password, err = utils.ReadBytes(reader)
	if err != nil {
		return err
	}
	p.MAC, err = utils.ReadStringNull(reader)
	if err != nil {
		return err
	}
	err = binary.Read(reader, endian, &p.IsCheat)
	if err != nil {
		return err
	}
	err = binary.Read(reader, endian, &p.ClientVersion)
	if err != nil {
		return err
	}
	return nil
}
