// Code generated by diho_bytes_generate -type CharacterScreen character_screen.go; DO NOT EDIT.

package packets

import (
	"bytes"
	"encoding/binary"
	utils "github.com/Nyarum/diho_bytes_generate/utils"
)

func (p *CharacterScreen) Decode(buf []byte, endian binary.ByteOrder) error {
	var err error
	reader := bytes.NewReader(buf)
	err = binary.Read(reader, endian, &p.ErrorCode)
	if err != nil {
		return err
	}
	p.Key, err = utils.ReadBytes(reader)
	if err != nil {
		return err
	}
	err = binary.Read(reader, endian, &p.CharacterLen)
	if err != nil {
		return err
	}
	err = binary.Read(reader, endian, &p.Pincode)
	if err != nil {
		return err
	}
	err = binary.Read(reader, endian, &p.Encryption)
	if err != nil {
		return err
	}
	err = binary.Read(reader, endian, &p.DWFlag)
	if err != nil {
		return err
	}
	return nil
}
