// Code generated by diho_bytes_generate character_screen.go; DO NOT EDIT.

package packets

import (
	"context"
	"encoding/binary"
	utils "github.com/Nyarum/diho_bytes_generate/utils"
	bytebufferpool "github.com/valyala/bytebufferpool"
)

func (p *CharacterScreen) Encode(ctx context.Context, endian binary.ByteOrder) ([]byte, error) {
	newBuf := bytebufferpool.Get()
	defer bytebufferpool.Put(newBuf)
	var err error
	err = binary.Write(newBuf, endian, p.ErrorCode)
	if err != nil {
		return nil, err
	}
	err = utils.WriteBytes(newBuf, p.Key)
	if err != nil {
		return nil, err
	}
	err = binary.Write(newBuf, endian, p.CharacterLen)
	if err != nil {
		return nil, err
	}
	err = binary.Write(newBuf, endian, p.Pincode)
	if err != nil {
		return nil, err
	}
	err = binary.Write(newBuf, endian, p.Encryption)
	if err != nil {
		return nil, err
	}
	err = binary.Write(newBuf, endian, p.DWFlag)
	if err != nil {
		return nil, err
	}
	return utils.Clone(newBuf), nil
}
