// Code generated by diho_bytes_generate -type FirstTime first_time.go; DO NOT EDIT.

package packets

import (
	"encoding/binary"
	utils "github.com/Nyarum/diho_bytes_generate/utils"
	bytebufferpool "github.com/valyala/bytebufferpool"
)

func (p *FirstTime) Encode(endian binary.ByteOrder) ([]byte, error) {
	newBuf := bytebufferpool.Get()
	defer bytebufferpool.Put(newBuf)
	var err error
	err = binary.Write(newBuf, endian, p.Opcode)
	if err != nil {
		return nil, err
	}
	err = utils.WriteStringNull(newBuf, p.Time)
	if err != nil {
		return nil, err
	}
	return utils.Clone(newBuf), nil
}
