// Code generated by diho_bytes_generate first_time.go; DO NOT EDIT.

package packets

import (
	"bytes"
	"context"
	"encoding/binary"
	utils "github.com/Nyarum/diho_bytes_generate/utils"
)

func (p *FirstTime) Decode(ctx context.Context, buf []byte, endian binary.ByteOrder) error {
	var err error
	reader := bytes.NewReader(buf)
	p.Time, err = utils.ReadStringNull(reader)
	if err != nil {
		return err
	}
	return nil
}
